version: "3.9"
services:
  web:
    build: .
    ports:
      - "0.0.0.0:3000:3000"
    environment: 
      - DB_HOST=db
      - DB_USER=registratie-website
      - DB_PASSWORD=changeme
      - DB_NAME=registratie-website # Optional, defaults to registratie-website
    links:
      - database:db
  database:
    image: mongo:4.9.0-rc1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=registratie-website
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    volumes: 
      - database:/data/db
volumes:
  database: